services:
  ocr:
    build: .
    image: paddleocr-my:v1
    container_name: ocr
    ports:
      - "80:82"
#    restart: always
    environment:
      TZ: "Asia/Shanghai"
networks:
  default:
    external: true
    name: nginx_default
